#! /usr/bin/env python

import json
import os
import sys

from common import get_payload
from common import get_version


def get(dst):
    print("Using dir {}".format(dst), file=sys.stderr)
    payload = get_payload()
    version = get_version(payload)

    with open(os.path.join(dst, 'version'), 'w') as fp:
        fp.write(version)

    print(json.dumps({
        'version': {'version': version},
        'metadata': []
    }))


if __name__ == '__main__':
    get(sys.argv[1])
